""" Copyright (c) 2020, Daniela Szwarcman and IBM Research
    * Licensed under The MIT License [see LICENSE for details]

    - Retrain CNN model generated by Q-NAS.
"""

import argparse
import os
import qnas_config as cfg
from util import check_files, init_log, save_results_file
from cnn import input
from cnn import train_detailed as train
import time

def main(**args):

    logger = init_log(args['log_level'], name=__name__)
    # Check if *experiment_path* contains all the necessary files to retrain an evolved model
    experiment_path = args['experiment_path']
    check_files(args['experiment_path'])

    # Get all parameters
    logger.info(f"Retraining evolved model {experiment_path} ...")
    config = cfg.ConfigParameters(args, phase='retrain')
    config.get_parameters()
    config.load_evolved_data(experiment_path=experiment_path)

    # Load data
    logger.info(f"Loading data ...")
    data_loader = input.GenericDataLoader(params=config.train_spec)
    train_loader, val_loader = data_loader.get_loader(pin_memory_device=args['device'])
    test_loader = data_loader.get_loader(for_train=False, pin_memory_device=args['device'])
    
    retrain_multi = []

    # Retrain model for the number of repetitions
    for i in range(1, args['num_repetitions']+1):
        logger.info(f"Retraining {experiment_path} repetition {i} ...")
        start_time = time.perf_counter()
        results = train.train_and_eval(params=config.train_spec, fn_dict=config.fn_dict, net_list=config.evolved_params['net'], 
                             train_loader=train_loader, val_loader=val_loader, test_loader=test_loader)
        retrain_multi.append(results)
        config.train_spec['experiment_path'] = os.path.join(experiment_path, f"retrain_{i+1}")
        
        end_time = time.perf_counter()
        hours, rem = divmod(end_time - start_time, 3600)
        mins, _ = divmod(rem, 60)
        logger.info(f"Retraining {experiment_path} repetition {i} finished in {int(hours):02d}h:{int(mins):02d}m.")


    # Save results
    logger.info(f"Saving results ...")
    save_results_file(out_path=experiment_path, results_list=retrain_multi, file_name='retrain_results.txt')

    logger.info(f"Retraining finished.")


if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--experiment_path', type=str, required=True,
                        help='Directory where the evolved network logs are.')
    parser.add_argument('--data_path', type=str, required=True, help='Path to input data.')
    parser.add_argument('--retrain_folder', type=str, default='retrain',
                        help='Name of the folder with retrain model files that will be saved '
                             'inside *experiment_path*.')

    # Training info
    parser.add_argument('--log_level', choices=['NONE', 'INFO', 'DEBUG'], default='NONE',
                        help='Logging information level.')
    parser.add_argument('--max_epochs', type=int, default=300,
                        help='The maximum number of epochs during training. Default = 300.')
    parser.add_argument('--batch_size', type=int, default=256,
                        help='Size of the batch that will be divided into multiple GPUs.'
                             ' Default = 128.')
    parser.add_argument('--eval_batch_size', type=int, default=1000,
                        help='Size of the evaluation batch. Default = 0 (which means the '
                             'entire validation dataset at once).')
    parser.add_argument('--limit_data', type=bool, default=False,
                        help='Limit the amount of data to be used during training. Default = False.')
    parser.add_argument('--device', type=str, default='cuda',
                        help='Device to be used during training. Default = cuda.')
    parser.add_argument('--num_repetitions', type=int, default=1,
                        help='Number of times the training will be repeated. Default = 1.')
    arguments = parser.parse_args()

    main(**vars(arguments))